### ISSUE TITLE
value binding - missing contry code

### ISSUE THREAD

**Issue by mxaly** [justin-lau/ember-intl-tel-input#1]
there is no country code when binding value.

**Comment by mxaly** [comment]
fix: https://github.com/mxaly/ember-intl-tel-input/commit/a3e0be5bc9d48f6b9ab60da88ad11d3dcd8602b7

but it force using `property` instead of `value` attribute:

``` js
{{intl-tel-input property=model.phone}}
```

**Comment by justin-lau** [comment]
@mxaly thanks for bringing this up, I have added [a few properties to bind](http://justin-lau.github.io/ember-intl-tel-input/#properties-binding) to in v1.1.0.
