### ISSUE TITLE
how do I access libphonenumber methods?

### ISSUE THREAD

**Issue by fredguth** [justin-lau/ember-intl-tel-input#10]
I would like to use PhoneNumberOfflineGeocoder from libphonenumber.

Any idea on how can I do that?

**Comment by justin-lau** [comment]
The [utilities script](https://github.com/jackocnr/intl-tel-input/blob/master/lib/libphonenumber/src/utils.js) from the original intl-tel-input is a custom build and it does not include the function you're after.

The easiest way to enable `PhoneNumberOfflineGeocoder` or other unsupported functions from `libphonenumber`, would be to include the original `libphonenumber` script your app's `vendor/`. This way the util script will be overwritten by the full featured version.

A more proper approach would be to fork this repo and replace the util script in [index.js](https://github.com/justin-lau/ember-intl-tel-input/blob/master/index.js#L13) by the complete original version. This way you won't get repeated, bulky scripts in the final build.

**Comment by fredguth** [comment]
Thanks!

Em ter, 24 de nov de 2015 às 06:50, Justin Lau notifications@github.com
escreveu:

**Comment by justin-lau** [comment]
You're welcome. I am closing this issue. If you have further questions feel free to bring this up again.
