### ISSUE TITLE
[question] how can I check libphonenumber version?

### ISSUE THREAD

**Issue by fredguth** [justin-lau/ember-intl-tel-input#15]
Hi,
Recently number rules changes in Brazil and I believe libphonenumber has already updated.  How can I check libphonenumber version in ember-intl-tel-input?

Thanks

**Comment by justin-lau** [comment]
It's `v7.0.6` according to the author of `intl-tel-input`. Feel free to submit a PR to update the dependencies!

**Comment by justin-lau** [comment]
I found the version number on the commit message: https://github.com/jackocnr/intl-tel-input/blob/v6.0.3/lib/libphonenumber/build/utils.js

**Comment by fredguth** [comment]
Thanks
