### ISSUE TITLE
[ember 1.13] browser freeze

### ISSUE THREAD

**Issue by mxaly** [justin-lau/ember-intl-tel-input#2]
looks like `number` property is not correctly calculated causing infinite loop with kills browser.

**Comment by justin-lau** [comment]
I haven't encountered this issue, can you please provide more details, such as OS and browser version, or better yet, a demo setup that reproduces the problem?

**Comment by mxaly** [comment]
nah, i can't reproduce it now - looks like it was some crazy issue on my machine.
Let's close this one.
