### ISSUE TITLE
country formatting is different than libphonenumber

### ISSUE THREAD

**Issue by fredguth** [justin-lau/ember-intl-tel-input#9]
Hi,
I am just using the demo and noticed that when I input this Brazilian phone number: 21981143100; there is no formatting working. When I use the libphonenumber demo:  
https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

it correctly formats.   

Why is that? Don't you use libphonenumber for formatting?

Thanks

**Comment by fredguth** [comment]
The issue happens only in the demo.  Installed the addon and it works.  Thanks

**Comment by justin-lau** [comment]
In case anyone else may have the same questions, the demo is running fine.

The first input box demonstrated the use of this plugin without the utilities script, thus no auto formatting supported.

The [properties binding example](http://justin-lau.github.io/ember-intl-tel-input/#properties-binding), on the other hand, can demonstrate most of the usage.

**Comment by fredguth** [comment]
oops.  My bad.  Thanks.

Em ter, 24 de nov de 2015 às 06:35, Justin Lau notifications@github.com
escreveu:
